"""Initial migration

Revision ID: 1b4758072b52
Revises: 
Create Date: 2025-07-22 15:07:05.088038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4758072b52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('default_watering_frequency', sa.Integer(), nullable=True),
    sa.Column('light_requirements', sa.String(), nullable=True),
    sa.Column('temperature_range', sa.String(), nullable=True),
    sa.Column('pet_safe', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('watering_frequency', sa.Integer(), nullable=True),
    sa.Column('last_watered_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watering_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_plant_id', sa.Integer(), nullable=False),
    sa.Column('watered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watering_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_plant_id', sa.Integer(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('last_watered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watering_schedules')
    op.drop_table('watering_records')
    op.drop_table('user_plants')
    op.drop_table('users')
    op.drop_table('plants')
    # ### end Alembic commands ###
