"""Updates User model to require zipcode only

Revision ID: 2dd1b0597b72
Revises: 04c3ac8fc52f
Create Date: 2025-07-22 18:14:26.466021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd1b0597b72'
down_revision = '04c3ac8fc52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.String(), nullable=False))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
