"""Updates User to store lat/lon info

Revision ID: 524bc4a8d061
Revises: bbe49aa1c275
Create Date: 2025-07-23 20:37:15.890550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524bc4a8d061'
down_revision = 'bbe49aa1c275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
