"""Updates field name to correct is_pet_safe for Plant model

Revision ID: 55d8181a8e4e
Revises: 78dc2dbcfc53
Create Date: 2025-07-28 16:34:47.231791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d8181a8e4e'
down_revision = '78dc2dbcfc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pet_safe', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_plant_safe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_plant_safe', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_pet_safe')

    # ### end Alembic commands ###
