"""add boolean weather_alerts_enabled to user model

Revision ID: 670b70ad549c
Revises: bae57e8b4ce5
Create Date: 2025-08-08 02:04:03.341403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670b70ad549c'
down_revision = 'bae57e8b4ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather_alerts_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('weather_alerts_enabled')

    # ### end Alembic commands ###
