"""Adds watering_reminders_enabled to User

Revision ID: 755c0b3d2ce8
Revises: 8c8a78dd3445
Create Date: 2025-08-07 14:31:17.299343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755c0b3d2ce8'
down_revision = '8c8a78dd3445'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'watering_reminders_enabled',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )
        batch_op.alter_column('watering_reminders_enabled', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('watering_reminders_enabled')

    # ### end Alembic commands ###
