"""Adds DailyWeather model

Revision ID: 78dc2dbcfc53
Revises: 524bc4a8d061
Create Date: 2025-07-24 15:27:05.939095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dc2dbcfc53'
down_revision = '524bc4a8d061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('min_temp', sa.Float(), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('did_rain', sa.Boolean(), nullable=False),
    sa.Column('weather_description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_weather', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_weather_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_weather', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_weather_date'))

    op.drop_table('daily_weather')
    # ### end Alembic commands ###
