"""Updated models to stickk to original proposal, adds __init__ and to_dict() methods

Revision ID: 87504db7a992
Revises: 1b4758072b52
Create Date: 2025-07-22 15:47:24.054498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87504db7a992'
down_revision = '1b4758072b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('species', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_soil_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('propagation_methods', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('edible_parts', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_plant_safe', sa.Boolean(), nullable=True))
        batch_op.alter_column('scientific_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_column('light_requirements')
        batch_op.drop_column('description')
        batch_op.drop_column('default_watering_frequency')
        batch_op.drop_column('temperature_range')
        batch_op.drop_column('pet_safe')
        batch_op.drop_column('name')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('user_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_outside', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('planted_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('last_watered_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('nickname')
        batch_op.drop_column('watering_frequency')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.drop_column('name')

    with op.batch_alter_table('user_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watering_frequency', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_watered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('planted_date')
        batch_op.drop_column('is_outside')

    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pet_safe', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temperature_range', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('default_watering_frequency', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('light_requirements', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('scientific_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('is_plant_safe')
        batch_op.drop_column('edible_parts')
        batch_op.drop_column('propagation_methods')
        batch_op.drop_column('preferred_soil_conditions')
        batch_op.drop_column('species')
        batch_op.drop_column('common_name')

    # ### end Alembic commands ###
