"""Edits Plant model structure

Revision ID: 878f1b278e14
Revises: 2b1343a3f1e4
Create Date: 2025-07-28 19:01:01.046347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878f1b278e14'
down_revision = '2b1343a3f1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('scientific_name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('common_name',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('common_name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('scientific_name',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
