"""Adds Tag model

Revision ID: 8c8a78dd3445
Revises: f7f87a9c9e61
Create Date: 2025-08-01 03:52:46.754013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8a78dd3445'
down_revision = 'f7f87a9c9e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('userplant_tags',
        sa.Column('user_plant_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
        sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ),
        sa.PrimaryKeyConstraint('user_plant_id', 'tag_id')
    )
    with op.batch_alter_table('user_plants', schema=None) as batch_op:
        # Add 'is_outdoor' with server default so existing rows get a valid value
        batch_op.add_column(sa.Column('is_outdoor', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.drop_column('is_outside')
    # Remove the server default for 'is_outdoor' now that it exists
    with op.batch_alter_table('user_plants', schema=None) as batch_op:
        batch_op.alter_column('is_outdoor', server_default=None)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garden_name', sa.String(), nullable=False, server_default="Your Garden"))
    # Remove default on garden_name to enforce explicit values later
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('garden_name', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('garden_name')

    with op.batch_alter_table('user_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_outside', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_outdoor')

    op.drop_table('userplant_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
