"""Adds to UserPlant to_dict

Revision ID: bae57e8b4ce5
Revises: 755c0b3d2ce8
Create Date: 2025-08-07 16:19:27.844946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae57e8b4ce5'
down_revision = '755c0b3d2ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('watering_reminders_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('watering_reminders_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
