"""Setting up db

Revision ID: bbe49aa1c275
Revises: 
Create Date: 2025-07-23 19:35:55.476890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe49aa1c275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.Text(), nullable=False),
    sa.Column('scientific_name', sa.Text(), nullable=False),
    sa.Column('species', sa.Text(), nullable=True),
    sa.Column('preferred_soil_conditions', sa.Text(), nullable=True),
    sa.Column('propagation_methods', sa.Text(), nullable=True),
    sa.Column('edible_parts', sa.Text(), nullable=True),
    sa.Column('is_plant_safe', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('is_outside', sa.Boolean(), nullable=False),
    sa.Column('planted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watering_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_plant_id', sa.Integer(), nullable=False),
    sa.Column('watered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watering_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_plant_id', sa.Integer(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('last_watered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watering_schedules')
    op.drop_table('watering_records')
    op.drop_table('user_plants')
    op.drop_table('users')
    op.drop_table('plants')
    # ### end Alembic commands ###
