"""Adds garden_name to User model

Revision ID: f7f87a9c9e61
Revises: 878f1b278e14
Create Date: 2025-08-01 03:13:53.984860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f87a9c9e61'
down_revision = '878f1b278e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garden_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('garden_name')

    # ### end Alembic commands ###
