name: Weather Alerts Cronjob

on:
  schedule:
    - cron: "0 17 * * *"  # runs daily at 9am PST
  workflow_dispatch:      # lets you trigger it manually from GitHub

jobs:
  run-weather-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weather alerts script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python cronjobs/run_weather_alerts.py
